version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /myapp/docker/username
    DOCKER_PASSWORD: /myapp/docker/password
    APP_DEBUG: /myapp/env/APP_DEBUG
    APP_ENV: /myapp/env/APP_ENV
    APP_KEY: /myapp/env/APP_KEY
    APP_NAME: /myapp/env/APP_NAME
    APP_URL: /myapp/env/APP_URL
    DB_CONNECTION: /myapp/env/DB_CONNECTION
    DB_DATABASE: /myapp/env/DB_DATABASE
    DB_HOST: /myapp/env/DB_HOST
    DB_PASSWORD: /myapp/env/DB_PASSWORD
    DB_PORT: /myapp/env/DB_PORT
    DB_USERNAME: /myapp/env/DB_USERNAME
    AWS_ACCESS_KEY_ID: ""
    AWS_BUCKET: ""
    AWS_DEFAULT_REGION: ""
    AWS_SECRET_ACCESS_KEY: ""
    AWS_USE_PATH_STYLE_ENDPOINT: /myapp/env/AWS_USE_PATH_STYLE_ENDPOINT
    BROADCAST_DRIVER: /myapp/env/BROADCAST_DRIVER
    CACHE_DRIVER: /myapp/env/CACHE_DRIVER
    FILESYSTEM_DISK: /myapp/env/FILESYSTEM_DISK
    LOG_CHANNEL: /myapp/env/LOG_CHANNEL
    LOG_DEPRECATIONS_CHANNEL: /myapp/env/LOG_DEPRECATIONS_CHANNEL
    LOG_LEVEL: /myapp/env/LOG_LEVEL
    MAIL_ENCRYPTION: /myapp/env/MAIL_ENCRYPTION
    MAIL_FROM_ADDRESS: /myapp/env/MAIL_FROM_ADDRESS
    MAIL_FROM_NAME: /myapp/env/MAIL_FROM_NAME
    MAIL_HOST: /myapp/env/MAIL_HOST
    MAIL_MAILER: /myapp/env/MAIL_MAILER
    MAIL_PASSWORD: /myapp/env/MAIL_PASSWORD
    MAIL_PORT: /myapp/env/MAIL_PORT
    MAIL_USERNAME: /myapp/env/MAIL_USERNAME
    MEMCACHED_HOST: /myapp/env/MEMCACHED_HOST
    MIX_PUSHER_APP_CLUSTER: /myapp/env/MIX_PUSHER_APP_CLUSTER
    MIX_PUSHER_APP_KEY: /myapp/env/MIX_PUSHER_APP_KEY
    PUSHER_APP_CLUSTER: /myapp/env/PUSHER_APP_CLUSTER
    PUSHER_APP_ID: ""
    PUSHER_APP_KEY: ""
    PUSHER_APP_SECRET: ""
    QUEUE_CONNECTION: /myapp/env/QUEUE_CONNECTION
    REDIS_HOST: /myapp/env/REDIS_HOST
    REDIS_PASSWORD: /myapp/env/REDIS_PASSWORD
    REDIS_PORT: /myapp/env/REDIS_PORT
    SESSION_DRIVER: /myapp/env/SESSION_DRIVER
    SESSION_LIFETIME: /myapp/env/SESSION_LIFETIME

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo Successfully logged into Docker
      - echo "Creating .env file"
      - echo "APP_DEBUG=$APP_DEBUG" >> .env
      - echo "APP_ENV=$APP_ENV" >> .env
      - echo "APP_KEY=$APP_KEY" >> .env
      - echo "APP_NAME=$APP_NAME" >> .env
      - echo "APP_URL=$APP_URL" >> .env
      - echo "DB_CONNECTION=$DB_CONNECTION" >> .env
      - echo "DB_DATABASE=$DB_DATABASE" >> .env
      - echo "DB_HOST=$DB_HOST" >> .env
      - echo "DB_USERNAME=$DB_USERNAME" >> .env
      - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
      - echo "DB_PORT=$DB_PORT" >> .env
      - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
      - echo "AWS_BUCKET=$AWS_BUCKET" >> .env
      - echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> .env
      - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
      - echo "AWS_USE_PATH_STYLE_ENDPOINT=$AWS_USE_PATH_STYLE_ENDPOINT" >> .env
      - echo "BROADCAST_DRIVER=$BROADCAST_DRIVER" >> .env
      - echo "CACHE_DRIVER=$CACHE_DRIVER" >> .env
      - echo "FILESYSTEM_DISK=$FILESYSTEM_DISK" >> .env
      - echo "LOG_CHANNEL=$LOG_CHANNEL" >> .env
      - echo "LOG_DEPRECATIONS_CHANNEL=$LOG_DEPRECATIONS_CHANNEL" >> .env
      - echo "LOG_LEVEL=$LOG_LEVEL" >> .env
      - echo "MAIL_ENCRYPTION=$MAIL_ENCRYPTION" >> .env
      - echo "MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS" >> .env
      - echo "MAIL_FROM_NAME=$MAIL_FROM_NAME" >> .env
      - echo "MAIL_HOST=$MAIL_HOST" >> .env
      - echo "MAIL_MAILER=$MAIL_MAILER" >> .env
      - echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .env
      - echo "MAIL_PORT=$MAIL_PORT" >> .env
      - echo "MEMCACHED_HOST=$MEMCACHED_HOST" >> .env
      - echo "MIX_PUSHER_APP_CLUSTER=$MIX_PUSHER_APP_CLUSTER" >> .env
      - echo "MIX_PUSHER_APP_KEY=$MIX_PUSHER_APP_KEY" >> .env
      - echo "PUSHER_APP_CLUSTER=$PUSHER_APP_CLUSTER" >> .env
      - echo "PUSHER_APP_ID=$PUSHER_APP_ID" >> .env
      - echo "PUSHER_APP_KEY=$PUSHER_APP_KEY" >> .env
      - echo "PUSHER_APP_SECRET=$PUSHER_APP_SECRET" >> .env
      - echo "QUEUE_CONNECTION=$QUEUE_CONNECTION" >> .env
      - echo "REDIS_HOST=$REDIS_HOST" >> .env
      - echo "REDIS_PASSWORD=$REDIS_PASSWORD" >> .env
      - echo "REDIS_PORT=$REDIS_PORT" >> .env
      - echo "SESSION_DRIVER=$SESSION_DRIVER" >> .env
      - echo "SESSION_LIFETIME=$SESSION_LIFETIME" >> .env

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t absharhassan/sims-app-main-image .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to dockerhub...
      - docker push absharhassan/sims-app-main-image
      - echo Build completed

artifacts:
  files:
    - "**/*"
