version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /myapp/docker/username
    DOCKER_PASSWORD: /myapp/docker/password
    APP_DEBUG: /myapp/env/APP_DEBUG
    APP_ENV: /myapp/env/APP_ENV
    APP_KEY: /myapp/env/APP_KEY
    APP_NAME: /myapp/env/APP_NAME
    APP_URL: /myapp/env/APP_URL
    DB_CONNECTION: /myapp/env/DB_CONNECTION
    DB_DATABASE: /myapp/env/DB_DATABASE
    DB_HOST: /myapp/env/DB_HOST
    DB_PASSWORD: /myapp/env/DB_PASSWORD
    DB_PORT: /myapp/env/DB_PORT
    DB_USERNAME: /myapp/env/DB_USERNAME

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo Successfully logged into Docker
      - echo "Creating .env file"
      - echo "APP_DEBUG=$APP_DEBUG" >> .env
      - echo "APP_ENV=$APP_ENV" >> .env
      - echo "APP_KEY=$APP_KEY" >> .env
      - echo "APP_NAME=$APP_NAME" >> .env
      - echo "APP_URL=$APP_URL" >> .env
      - echo "DB_CONNECTION=$DB_CONNECTION" >> .env
      - echo "DB_DATABASE=$DB_DATABASE" >> .env
      - echo "DB_HOST=$DB_HOST" >> .env
      - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
      - echo "DB_PORT=$DB_PORT" >> .env
      - echo "DB_USERNAME=$DB_USERNAME" >> .env

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t absharhassan/sims-app-main-image .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to dockerhub...
      - docker push absharhassan/sims-app-main-image
      - echo Build completed

artifacts:
  files:
    - "**/*"
