version: "3.8"

services:
    web:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "80:80"

        volumes:
            - .:/var/www/html
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        links:
            - app
        restart: always
        # networks:
        #     - app-network
    app:
        container_name: laravel_app
        image: absharhassan/sims-app-main-image:latest
        # build: .
        # ports:
        #     - 8000:8000
        volumes:
            - /var/www/html/vendor
            - /var/www/html/node_modules
            - .:/var/www/html
        restart: always
        # networks:
        #     - app-network
        depends_on:
            - db
    db:
        container_name: mysql_db
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

#Docker Networks
# networks:
#     app-network:
#         driver: bridge
volumes:
    db-data: ~
